"""Curated ingredient library for shopping decisions.

This is not a medical database and it is not the Royal Society of Chemistry
classroom handout that was stored with the first upload. That handout is a
school worksheet. Several of its lines are wrong, so it is not used here.
"""

from __future__ import annotations


def ing(id_, names, display, role, summary, short, long, rules=None):
    return {
        "id": id_,
        "names": names,
        "display": display,
        "role": role,
        "summary": summary,
        "short_term": short,
        "long_term": long,
        "rules": rules or [],
    }


def A(reason):
    return {"if": "always", "level": "avoid", "reason": reason}


def C(flag, reason):
    return {"if": flag, "level": "caution", "reason": reason}


def H(flag, reason):
    return {"if": flag, "level": "helpful", "reason": reason}


def V(flag, reason):
    return {"if": flag, "level": "avoid", "reason": reason}


INGREDIENTS = [
    ing(
        "clobetasol",
        ["clobetasol", "clobetasol propionate", "tenovate", "lobate", "clobetamil"],
        "Clobetasol propionate",
        "Steroid drug",
        "One of the strongest steroid medicines. It does not belong in a cream you buy from a reel or a shop link.",
        "Within days it can flatten redness and feel like a miracle. That effect is the drug, not a cure for pigmentation.",
        "Over weeks it can thin skin, cause pimples, facial hair, and visible veins. When you stop, darkness and redness often come back worse. Do not use it unless a doctor who has seen your skin prescribed this exact tube.",
        [A("This is a strong steroid medicine, not a cosmetic. Do not buy it from an influencer."),
         V("steroid_med", "You already use a steroid. Adding another one from a shop is how facial skin gets damaged."),
         V("child", "Do not put a strong steroid on a child because a video recommended it.")],
    ),
    ing(
        "betamethasone",
        ["betamethasone", "betamethasone valerate", "betamethasone dipropionate", "betnovate", "diprovate", "betamil"],
        "Betamethasone",
        "Steroid drug",
        "A prescription steroid widely misused in fairness and 'glow' creams.",
        "It can calm redness quickly. People mistake that calm for healing.",
        "Continued use can thin skin and cause steroid dependence. Stopping often brings a worse rebound of redness and dark patches. This is a drug, not a beauty product.",
        [A("Betamethasone is a steroid medicine. Do not use it because a post told you it would brighten skin."),
         V("steroid_med", "You already use a steroid. Do not add another steroid cream on top."),
         V("child", "Do not use this on a child unless a paediatric dermatologist prescribed this exact product.")],
    ),
    ing(
        "mometasone",
        ["mometasone", "mometasone furoate", "momate", "momtas", "elocon"],
        "Mometasone",
        "Steroid drug",
        "A prescription steroid. It shows up in illegal mixed creams sold for spots and fairness.",
        "Redness can drop quickly, which is the drug working on inflammation, not on the root problem.",
        "Weeks of use can thin skin and cause acne, facial hair, and rebound darkness after you stop.",
        [A("Mometasone is a steroid medicine. A shop or a reel is the wrong place to start it."),
         V("steroid_med", "You already use a steroid. Do not stack another one."),
         V("child", "Do not use this on a child from a cosmetic recommendation.")],
    ),
    ing(
        "fluocinolone",
        ["fluocinolone", "fluocinolone acetonide"],
        "Fluocinolone acetonide",
        "Steroid drug",
        "A steroid often hidden inside 'triple combination' fade creams, next to hydroquinone and tretinoin.",
        "The mix can look effective within days because the steroid suppresses redness.",
        "Unsupervised use is a common cause of steroid-damaged face and rebound pigmentation. Only a dermatologist should prescribe a combination like this.",
        [A("Fluocinolone is a steroid. Do not start a combination fade cream from a shopping link.")],
    ),
    ing(
        "hydrocortisone",
        ["hydrocortisone", "hydrocortisone acetate"],
        "Hydrocortisone",
        "Steroid drug",
        "A milder steroid than clobetasol, and still a medicine.",
        "It can ease itch for a short time. It is not a pigment or acne treatment.",
        "Using it for weeks on the face because a video said so can still thin skin and trigger rebound trouble. Use it only if your own clinician told you to.",
        [A("Hydrocortisone is a medicine. Do not pick it up as a cosmetic from an influencer link.")],
    ),
    ing(
        "mercury",
        ["mercury", "mercuric chloride", "mercurous chloride", "calomel", "ammoniated mercury", "mercury chloride"],
        "Mercury",
        "Toxic contaminant",
        "Mercury compounds have been found in illegal skin-lightening creams. They are poisonous.",
        "Do not apply this. Mercury can pass through skin.",
        "Repeated use can harm the kidneys and the nervous system. Stop, and tell a doctor if you have already used it for a while.",
        [A("Mercury does not belong in a cosmetic. Do not buy or apply this product.")],
    ),
    ing(
        "hydroquinone",
        ["hydroquinone", "hydroquinol"],
        "Hydroquinone",
        "Prescription drug",
        "A drug for dark patches. It is not an ordinary cosmetic active, and COSMIX does not treat whitening as a benefit.",
        "Do not start hydroquinone from a shop link or a reel.",
        "Months of unsupervised use can cause a blue-black darkening called exogenous ochronosis, especially on medium and deep skin. It is also avoided in pregnancy. A dermatologist has to decide whether you need it.",
        [A("Do not start hydroquinone from a shopping link. It is a drug with real long-term risks."),
         V("pregnancy", "Hydroquinone is not something to start while pregnant, breastfeeding, or trying to conceive."),
         V("child", "Do not use hydroquinone on a child from a cosmetic recommendation.")],
    ),
    ing(
        "tretinoin",
        ["tretinoin", "retinoic acid", "all trans retinoic acid", "retin-a", "retino-a"],
        "Tretinoin",
        "Prescription drug",
        "A prescription retinoid used for acne and photoaging. Stronger and harsher than cosmetic retinol.",
        "Expect dryness, peeling, and sting in the first weeks if a doctor has actually prescribed it. Do not begin it from a video.",
        "Used correctly, under a doctor, it has real evidence for acne and sun-damaged skin. Used from an unlabelled mix, it burns the barrier and is dangerous in pregnancy.",
        [V("always", "Tretinoin is a prescription medicine. Do not use a product that contains it because a reel recommended it. If your dermatologist prescribed this exact product, follow that doctor."),
         V("pregnancy", "Retinoids are avoided in pregnancy and while trying to conceive."),
         V("child", "Do not use tretinoin on a young child from a cosmetic post."),
         V("isotretinoin", "Do not stack tretinoin on top of oral isotretinoin unless the prescribing doctor said to.")],
    ),
    ing(
        "isotretinoin_ingredient",
        ["isotretinoin", "accutane", "13 cis retinoic acid"],
        "Isotretinoin",
        "Prescription drug",
        "An oral acne drug. It should not appear as a casual cosmetic ingredient.",
        "Do not apply or swallow a product sold like a normal cream ingredient.",
        "Oral isotretinoin causes severe birth defects if taken in pregnancy. It is a specialist drug, not a beauty product.",
        [A("Isotretinoin is a powerful drug. It does not belong in an influencer cosmetic.")],
    ),
    ing(
        "adapalene",
        ["adapalene"],
        "Adapalene",
        "Prescription drug",
        "A retinoid medicine for acne. In some countries a low strength is sold over the counter. It is still a drug.",
        "Dryness and peeling are common for the first month.",
        "It has real evidence for acne when the strength and the routine are right. It is not for pregnancy, and it should not be mixed casually with acids and scrubs.",
        [C("always", "Use adapalene only if a doctor or a pharmacist directed this product for you. It is a drug, not a simple serum."),
         V("pregnancy", "Do not use adapalene while pregnant, breastfeeding, or trying to conceive."),
         V("child", "Do not use adapalene on a young child from a cosmetic post."),
         H("acne", "Adapalene is one of the ingredients with real evidence for acne, when a clinician is guiding it."),
         V("isotretinoin", "Do not add adapalene while you are on oral isotretinoin unless your doctor said to.")],
    ),
    ing(
        "minoxidil",
        ["minoxidil"],
        "Minoxidil",
        "Prescription drug",
        "A drug for hair shedding, sold as a scalp lotion or foam. Not a face cosmetic.",
        "Some people get scalp itch or extra facial hair where it drips.",
        "It has evidence for certain kinds of hair loss, and the hair gained is often lost if you stop. Do not use it in pregnancy. A doctor should confirm why the hair is shedding before you start.",
        [C("always", "Minoxidil is a drug. Confirm the cause of hair loss before you buy it from an ad."),
         V("pregnancy", "Do not use minoxidil while pregnant, breastfeeding, or trying to conceive."),
         H("hair", "If a doctor has said your shedding is the type minoxidil can help, this is a relevant ingredient.")],
    ),
    ing(
        "ketoconazole",
        ["ketoconazole"],
        "Ketoconazole",
        "Active",
        "An antifungal used in medicated dandruff shampoos.",
        "As a wash, many people tolerate it. Leave it on the scalp only as the label or your doctor says.",
        "It can help dandruff driven by yeast. It is not a hair-growth drug. Ask a doctor before using it in pregnancy or on broken skin.",
        [H("dandruff", "Ketoconazole is a standard anti-dandruff antifungal when yeast is part of the problem."),
         C("pregnancy", "Ask your doctor before using ketoconazole while pregnant or breastfeeding.")],
    ),
    ing(
        "retinol",
        ["retinol"],
        "Retinol",
        "Active",
        "A vitamin A ingredient used for texture and photoaging. It irritates while the skin gets used to it.",
        "For two to six weeks many people peel, dry out, or sting. That is common. A broken, burning face is not a sign to push harder.",
        "If the skin tolerates it, retinol has better evidence than most anti-aging claims. It will not replace sunscreen. Do not use it in pregnancy.",
        [V("pregnancy", "Stop retinol while pregnant, breastfeeding, or trying to conceive, unless your own doctor makes a different call."),
         V("child", "Do not use retinol on a young child."),
         C("teen", "Teens do not need anti-aging retinol. A doctor should guide acne retinoids instead."),
         C("sensitive", "Sensitive skin often needs a very slow start, or a different ingredient."),
         C("eczema", "Retinol commonly flares eczema. Fix the barrier first."),
         C("rosacea", "Retinol often worsens burning and flushing."),
         C("barrier", "A damaged barrier and retinol together usually means more peeling, not more progress."),
         C("isotretinoin", "You are on isotretinoin. Do not add retinol unless your doctor says the skin can handle it."),
         C("retinoid_med", "You already use a prescription retinoid. A second retinol product is often too much."),
         H("aging", "Retinol is one of the few cosmetic ingredients with real evidence for photoaged skin, if you can tolerate it.")],
    ),
    ing(
        "retinaldehyde",
        ["retinaldehyde", "retinal"],
        "Retinal (retinaldehyde)",
        "Active",
        "A vitamin A ingredient, usually stronger-feeling than retinol. The word on labels is often 'retinal'.",
        "Dryness and peeling are common at the start.",
        "It can help texture over months if tolerated. Avoid it in pregnancy. It is not a substitute for a prescribed tretinoin plan.",
        [V("pregnancy", "Avoid retinal while pregnant, breastfeeding, or trying to conceive."),
         V("child", "Do not use retinal on a young child."),
         C("sensitive", "Retinal is often too harsh for sensitive skin at the start."),
         C("eczema", "This can flare eczema."),
         C("rosacea", "This can worsen burning and flushing."),
         C("barrier", "Do not add retinal on a broken skin barrier."),
         C("isotretinoin", "Do not stack retinal with oral isotretinoin unless your doctor said to."),
         C("retinoid_med", "You already use a prescription retinoid. Adding retinal is often too much."),
         H("aging", "Retinal is a serious anti-aging active if your skin can tolerate it.")],
    ),
    ing(
        "retinyl_palmitate",
        ["retinyl palmitate", "vitamin a palmitate"],
        "Retinyl palmitate",
        "Active",
        "A milder vitamin A ingredient. Evidence that it changes wrinkles is weaker than for retinol.",
        "Usually gentler than retinol, but it can still irritate.",
        "Do not treat it as the safe retinoid for pregnancy. The cautious advice is still to avoid vitamin A derivatives then.",
        [V("pregnancy", "Avoid vitamin A derivatives, including retinyl palmitate, in pregnancy and while trying to conceive."),
         C("sensitive", "Stop if you sting or peel."),
         C("eczema", "Can irritate eczema even though it is milder than retinol.")],
    ),
    ing(
        "salicylic",
        ["salicylic acid", "salicylic", "betaine salicylate", "salix alba", "willow bark", "willowbark"],
        "Salicylic acid",
        "Active",
        "An oil-soluble acid used for clogged pores and blackheads. Willow bark is in the same family.",
        "It can sting, especially on broken skin. Over a few weeks of careful use, some clogged pores loosen.",
        "Useful for many acne routines. Too much, too often, damages the barrier. Leave-on salicylic acid in pregnancy should be a doctor's decision. Related to aspirin.",
        [V("salicylate_allergy", "You flagged a salicylate or aspirin allergy. Salicylic acid and willow bark are in that family."),
         V("child", "Do not use salicylic acid leave-on products on a young child."),
         C("pregnancy", "Ask your doctor before leave-on salicylic acid in pregnancy. A wash-off product is a different, usually smaller, exposure."),
         C("sensitive", "Acids sting sensitive skin. Start rarely, not every day."),
         C("eczema", "Salicylic acid often burns eczema."),
         C("rosacea", "It can worsen rosacea burning."),
         C("barrier", "Do not put acids on a damaged barrier."),
         C("isotretinoin", "You are on isotretinoin. Acids usually wait until your doctor restarts them."),
         H("acne", "Salicylic acid is a standard ingredient for clogged pores and blackheads."),
         C("high_on_list", "It sits near the top of the list, so the dose may be meaningful. Introduce it slowly.")],
    ),
    ing(
        "glycolic",
        ["glycolic acid", "glycolic"],
        "Glycolic acid",
        "Active",
        "A small acid that speeds surface exfoliation. It also makes sunburn more likely.",
        "Sting and redness are common at the start. Use sunscreen in the daytime while you use it.",
        "Can improve dullness and rough texture over months. It scars confidence more than skin when people layer it with retinoids and scrubs. Not for a broken barrier.",
        [V("child", "Do not use glycolic acid on a young child."),
         C("pregnancy", "Ask your doctor before leave-on glycolic acid in pregnancy."),
         C("sensitive", "Glycolic acid is one of the stingier acids."),
         C("eczema", "It commonly burns eczema."),
         C("rosacea", "It commonly worsens rosacea."),
         C("barrier", "Do not exfoliate a damaged barrier."),
         C("isotretinoin", "Acids usually wait while you are on isotretinoin."),
         H("aging", "Glycolic acid has evidence for rough, sun-dull texture when the skin tolerates it and you use sunscreen."),
         H("pigmentation", "It can help some uneven tone slowly, with sunscreen. It is not a bleach."),
         C("high_on_list", "A high place on a leave-on list means a stronger effect and a higher chance of sting.")],
    ),
    ing(
        "lactic",
        ["lactic acid", "lactic"],
        "Lactic acid",
        "Active",
        "An exfoliating acid that is often gentler than glycolic acid. It still makes skin more sensitive to sun.",
        "Can sting on sensitive or cracked skin. Use sunscreen during the day.",
        "Can smooth rough skin over time. Stop if you are getting raw or shiny, tight irritation.",
        [C("pregnancy", "Ask your doctor before leave-on lactic acid in pregnancy."),
         C("sensitive", "Gentler than glycolic acid does not mean it cannot sting you."),
         C("eczema", "Acids often hurt eczema."),
         C("rosacea", "Can worsen flushing and burn."),
         C("barrier", "Do not use acids on a damaged barrier."),
         C("isotretinoin", "Wait on acids while you are on isotretinoin, unless your doctor said otherwise."),
         V("child", "Do not use leave-on acids on a young child."),
         H("dry", "Lactic acid can help a rough, dry surface when the barrier is otherwise healthy."),
         H("aging", "It can improve rough texture over time, with sunscreen.")],
    ),
    ing(
        "mandelic",
        ["mandelic acid", "mandelic"],
        "Mandelic acid",
        "Active",
        "A larger exfoliating acid, often slower and gentler than glycolic acid.",
        "Still an acid: sting means slow down. Use sunscreen.",
        "Sometimes chosen for acne-prone and uneven tone because it is less aggressive. Evidence is thinner than for salicylic acid or glycolic acid.",
        [C("sensitive", "Start slowly. Gentler does not mean inert."),
         C("eczema", "Skip acids while eczema is active."),
         C("rosacea", "Can still burn rosacea."),
         C("barrier", "Do not use this on a broken barrier."),
         C("pregnancy", "Ask your doctor before leave-on mandelic acid in pregnancy."),
         C("isotretinoin", "Acids usually wait during isotretinoin."),
         V("child", "Do not use leave-on acids on a young child."),
         H("acne", "Mandelic acid is sometimes better tolerated than glycolic acid for acne-prone skin."),
         H("pigmentation", "It may slowly help uneven tone. Sunscreen does more of the long-term work.")],
    ),
    ing(
        "azelaic",
        ["azelaic acid", "azelaic"],
        "Azelaic acid",
        "Active",
        "An ingredient used for acne and for some kinds of uneven pigment. It can itch at the start.",
        "Itch or sting in the first two weeks is common and often settles. A raw, worsening rash is a stop signal.",
        "One of the more useful leave-on ingredients if you have both spots and pigmentation. Prescription strengths are stronger than many cosmetic ones. Often discussed as an option in pregnancy, but that is still your doctor's call.",
        [C("sensitive", "Azelaic acid can itch even though it is not a classic acid peel."),
         C("barrier", "It can sting a broken barrier. Repair first."),
         H("acne", "Azelaic acid has real evidence for acne."),
         H("pigmentation", "It can help some dark marks and melasma as part of a plan, not overnight."),
         H("rosacea", "Azelaic acid is one of the ingredients clinicians actually use for rosacea-prone skin.")],
    ),
    ing(
        "benzoyl_peroxide",
        ["benzoyl peroxide"],
        "Benzoyl peroxide",
        "Active",
        "An acne ingredient that kills acne bacteria and can bleach fabric.",
        "Dryness and sting are common. It bleaches pillowcases and collars.",
        "Strong evidence for inflammatory acne. It is harsh with retinoids and on isotretinoin. It is not a spot-lightening cream.",
        [C("sensitive", "Benzoyl peroxide is drying. Sensitive skin needs a low strength and short contact."),
         C("eczema", "It often burns eczema."),
         C("rosacea", "It can worsen rosacea. It is an acne ingredient, not a rosacea one."),
         C("barrier", "Do not put this on a damaged barrier."),
         V("isotretinoin", "Do not use benzoyl peroxide while you are on oral isotretinoin unless your doctor said to."),
         C("retinoid_med", "Benzoyl peroxide plus a prescription retinoid is a harsh pair. Ask the prescriber before you combine them."),
         H("acne", "Benzoyl peroxide is one of the best-evidenced acne ingredients."),
         V("child", "Do not use benzoyl peroxide on a young child unless a doctor prescribed it.")],
    ),
    ing(
        "niacinamide",
        ["niacinamide", "nicotinamide", "vitamin b3"],
        "Niacinamide",
        "Active",
        "Vitamin B3. Widely used for oil control, uneven tone, and barrier support. Usually well tolerated.",
        "A few people flush or itch. Most people feel nothing dramatic in the first week, and that is normal.",
        "Over months it can help shine, redness, and uneven tone for some people. It will not replace a prescription for severe acne or melasma.",
        [H("acne", "Niacinamide is a reasonable supporting ingredient for oily, spot-prone skin. It is not an antibiotic."),
         H("pigmentation", "It can slowly help uneven tone. Think months, not seven days."),
         H("oily", "It can reduce the look of shine for some people."),
         H("barrier", "It is often used while a damaged barrier is recovering."),
         C("sensitive", "Most sensitive skin tolerates it. If you flush or itch, stop and retry less often.")],
    ),
    ing(
        "ascorbic",
        ["ascorbic acid", "l ascorbic acid", "vitamin c"],
        "Vitamin C (ascorbic acid)",
        "Active",
        "The pure form of vitamin C. It can brighten the look of dull skin and it stings more than the gentler derivatives.",
        "Sting is common, especially above the low percentages and on damp, sensitive skin. It also goes brown in the bottle when it has oxidised. A brown serum is past its best.",
        "Decent evidence for photoaging and uneven tone over months, if the product stays stable and you use sunscreen. It does not bleach skin.",
        [H("pigmentation", "Ascorbic acid can slowly help uneven tone and dullness. It is not a bleach and it needs sunscreen."),
         H("aging", "It has evidence as an antioxidant for sun-exposed skin."),
         C("sensitive", "Pure ascorbic acid stings sensitive skin. A derivative may be easier."),
         C("rosacea", "The low pH often burns rosacea."),
         C("barrier", "Do not start strong vitamin C on a broken barrier.")],
    ),
    ing(
        "ascorbyl_glucoside",
        ["ascorbyl glucoside", "sodium ascorbyl phosphate", "magnesium ascorbyl phosphate", "ascorbyl tetraisopalmitate", "ethyl ascorbic acid"],
        "Vitamin C derivative",
        "Active",
        "A gentler vitamin C form. Usually less sting, and usually less direct evidence than pure ascorbic acid.",
        "Most people tolerate these better than ascorbic acid. Do not expect a change in the first week.",
        "Can be a sensible vitamin C if your skin hates acids. Sunscreen still does the protective work.",
        [H("pigmentation", "A vitamin C derivative may slowly support uneven tone, with less sting than pure ascorbic acid."),
         H("sensitive", "This is often an easier vitamin C if pure ascorbic acid burns you."),
         C("barrier", "Even gentle vitamin C can wait until a raw barrier has calmed.")],
    ),
    ing(
        "hyaluronic",
        ["hyaluronic acid", "sodium hyaluronate", "hydrolyzed hyaluronic acid", "hyaluronate"],
        "Hyaluronic acid",
        "Active",
        "A moisture-binding ingredient. It does not replace a moisturiser on very dry skin, and it is not an acid peel.",
        "It should not sting. If the air is very dry and you use it alone, skin can feel tighter, so put a moisturiser on top.",
        "Helps skin hold water while you use it. It does not rebuild collagen in a serum the way advertisements imply.",
        [H("dry", "Hyaluronic acid helps dry skin hold water when you seal it with a moisturiser."),
         H("barrier", "It is a reasonable hydration ingredient while a barrier recovers."),
         H("sensitive", "The ingredient itself is usually calm. Sting is more often from something else in the bottle.")],
    ),
    ing(
        "ceramide",
        ["ceramide", "ceramides", "ceramide np", "ceramide ap", "ceramide eop", "ceramide ng"],
        "Ceramides",
        "Active",
        "Lipids that skin already uses in its barrier. In a cream they help reduce water loss.",
        "Should feel plain and soothing. They do not exfoliate.",
        "Useful for months of barrier repair. They will not clear acne by themselves.",
        [H("dry", "Ceramides are a sound choice for dry skin."),
         H("barrier", "Ceramides are standard ingredients while a damaged barrier recovers."),
         H("eczema", "Ceramide creams are often part of eczema care. The rest of the formula still has to be free of your triggers."),
         H("sensitive", "Usually a low-drama moisturising ingredient.")],
    ),
    ing(
        "centella",
        ["centella asiatica", "centella", "madecassoside", "asiaticoside", "gotu kola", "cica"],
        "Centella asiatica",
        "Active",
        "A plant used for calming care. Evidence is milder than advertisements suggest. 'Cica' on a label usually means this plant.",
        "Often feels soothing. Itch or a new rash means you may be reacting to the plant or to something else in the product.",
        "A reasonable supporting ingredient for irritation. It does not replace treatment for eczema, infection, or melasma.",
        [H("sensitive", "Centella is often used to calm irritation. Patch test if plant extracts bother you."),
         H("barrier", "A reasonable calming extra while the barrier recovers."),
         C("eczema", "Plant extracts can soothe or they can become the allergen. Stop if eczema spreads.")],
    ),
    ing(
        "tranexamic",
        ["tranexamic acid", "tranexamic"],
        "Tranexamic acid",
        "Active",
        "Used in some products for dark patches and melasma. Topical cosmetic strengths are not the same as the oral medicine.",
        "Usually tolerated. Do not expect fading in a week.",
        "Can help some uneven pigment over months, with sunscreen. Oral tranexamic acid is a different drug with clot risks and is not what this ingredient line means. Do not start the tablet from a cosmetic label.",
        [H("pigmentation", "Topical tranexamic acid is a relevant ingredient for uneven pigment, including melasma, with sunscreen."),
         C("pregnancy", "Ask your doctor before tranexamic acid in pregnancy, even the topical form.")],
    ),
    ing(
        "arbutin",
        ["alpha-arbutin", "arbutin", "beta arbutin"],
        "Arbutin",
        "Active",
        "A pigment-fading ingredient related to hydroquinone, used at cosmetic strengths. COSMIX does not score whitening as a goal.",
        "Usually calmer than acids. Any fade, if it happens, is slow.",
        "May slowly help dark marks from acne. It is not a licence to lighten your natural skin colour, and sunscreen matters more.",
        [H("pigmentation", "Arbutin may slowly help acne marks and uneven tone. It will not safely bleach skin."),
         C("pregnancy", "Ask your doctor before arbutin in pregnancy. It is in the hydroquinone family.")],
    ),
    ing(
        "kojic",
        ["kojic acid", "kojic"],
        "Kojic acid",
        "Active",
        "A pigment-fading ingredient that can irritate and can destabilise in the jar.",
        "Sting and redness are fairly common.",
        "Some evidence for dark marks. Also a known cause of allergic rash for some people. Not a whitening plan.",
        [H("pigmentation", "Kojic acid may help some dark marks and may also cause a rash. Sunscreen still leads."),
         C("sensitive", "Kojic acid irritates sensitive skin more often than niacinamide does."),
         C("eczema", "Skip kojic acid on active eczema."),
         C("pregnancy", "Ask your doctor before kojic acid in pregnancy.")],
    ),
    ing(
        "licorice",
        ["glycyrrhiza glabra", "glycyrrhiza inflata", "licorice", "liquorice", "glabridin", "dipotassium glycyrrhizate"],
        "Licorice root",
        "Active",
        "A plant extract used to calm and to fade the look of redness or marks. Doses on cosmetic labels vary wildly.",
        "Often gentle. A new itch means stop.",
        "A mild supporting ingredient, not a melasma treatment on its own.",
        [H("pigmentation", "Licorice is a mild supporting ingredient for uneven tone, not a standalone treatment."),
         H("sensitive", "Often included to calm redness. Stop if you itch.")],
    ),
    ing(
        "tea_tree",
        ["melaleuca alternifolia", "tea tree", "tea tree oil", "tea tree leaf oil"],
        "Tea tree oil",
        "Active",
        "An essential oil with some evidence for mild acne, and a real record of irritation and allergy.",
        "Neat oil can burn. In a formula it can still itch within days.",
        "Diluted, it can help some mild acne. It is a common allergen if you keep using it after you itch. Not for young children, and not something to swallow.",
        [V("tea_tree_allergy", "You flagged a tea tree allergy. Do not use this."),
         V("child", "Do not use tea tree oil on a young child."),
         C("sensitive", "Tea tree is a classic irritant for sensitive skin."),
         C("eczema", "Essential oils often flare eczema."),
         C("rosacea", "It can burn rosacea."),
         C("pregnancy", "Skip tea tree oil in pregnancy unless your doctor says otherwise."),
         H("acne", "Diluted tea tree has some evidence for mild acne, if your skin is not sensitive to it.")],
    ),
    ing(
        "zinc_pca",
        ["zinc pca", "zinc gluconate", "zinc sulfate"],
        "Zinc salt",
        "Active",
        "Zinc salts are used for oiliness and sometimes in acne routines. This is not zinc oxide sunscreen.",
        "Usually quiet on the skin.",
        "A supporting ingredient for oily skin, not a full acne treatment.",
        [H("oily", "Zinc salts can help the look of oily skin."),
         H("acne", "A reasonable supporting ingredient for acne-prone skin.")],
    ),
    ing(
        "zinc_pyrithione",
        ["zinc pyrithione"],
        "Zinc pyrithione",
        "Active",
        "An anti-dandruff ingredient. The EU has restricted it in cosmetics. Do not use it as a leave-on face cream.",
        "In a shampoo, many people tolerate a short contact. On the face, it is more likely to irritate.",
        "Can help dandruff. It is not a growth serum. Regulations around it have tightened because of safety concerns at cosmetic doses.",
        [C("leave_on", "Do not use zinc pyrithione as a leave-on face product."),
         H("dandruff", "It is a known anti-dandruff ingredient in wash-off hair products."),
         C("sensitive", "It can irritate sensitive skin."),
         C("pregnancy", "Ask your doctor before using zinc pyrithione in pregnancy.")],
    ),
    ing(
        "bakuchiol",
        ["bakuchiol"],
        "Bakuchiol",
        "Active",
        "A plant ingredient marketed as a gentler retinol alternative. The evidence is much smaller than for retinol.",
        "Usually gentler than retinol. It can still irritate.",
        "Reasonable to try if you cannot use retinol. Do not expect retinol-level evidence. It is not a drug.",
        [H("aging", "Bakuchiol is a milder option people use when retinol is too harsh. Evidence is limited."),
         C("sensitive", "Stop if you sting. Plant extracts are not automatically gentle."),
         C("pregnancy", "It is not a retinoid, but pregnancy data is thin. Ask your doctor before you rely on it.")],
    ),
    ing(
        "panthenol",
        ["panthenol", "dexpanthenol", "vitamin b5"],
        "Panthenol",
        "Active",
        "Vitamin B5. A common moisturising and soothing ingredient in both skin and hair products.",
        "Should not sting. It will not change acne or pigment this week.",
        "A solid, boring humectant. Good in barrier care. Weak as an 'anti-hair-loss' claim.",
        [H("dry", "Panthenol helps dry skin hold water."),
         H("barrier", "A standard soothing moisturiser ingredient."),
         H("sensitive", "Usually well tolerated.")],
    ),
    ing(
        "tocopherol",
        ["tocopherol", "tocopheryl acetate", "vitamin e"],
        "Vitamin E",
        "Active",
        "An antioxidant and oil-soluble moisturiser. A few people get allergic rashes from it.",
        "Usually uneventful. A new itchy rash can be a vitamin E allergy.",
        "Helps stop oils in the formula going rancid and can soften skin. It is not a wrinkle eraser.",
        [H("dry", "Vitamin E oils can soften dry skin."),
         C("sensitive", "A minority of people develop an allergy to vitamin E. Stop if you get a new itchy rash.")],
    ),
    ing(
        "allantoin",
        ["allantoin"],
        "Allantoin",
        "Active",
        "A soothing, smoothing ingredient used in calming creams.",
        "Should feel plain.",
        "A useful extra in barrier creams. Not a treatment for disease.",
        [H("sensitive", "Allantoin is usually calming."), H("barrier", "Fine in a barrier-repair cream.")],
    ),
    ing(
        "urea_cosmetic",
        ["urea"],
        "Urea",
        "Active",
        "At low percentages, a moisturiser. At higher percentages, a keratolytic that softens thick skin. The label often hides which one you are getting.",
        "Low strengths feel hydrating. High strengths can sting cracked skin.",
        "Very useful for dry, thick skin when the percentage matches the job. A 40% foot product is not a face serum.",
        [H("dry", "Urea is one of the better ingredients for dry, rough skin when the strength is right."),
         C("sensitive", "Higher strengths sting sensitive or cracked skin."),
         C("eczema", "Low-strength urea can help eczema dryness. High-strength urea can burn it. The label should tell you the percentage."),
         C("barrier", "Do not use a high-strength urea product on a raw face.")],
    ),
    ing(
        "sulfur",
        ["sulfur", "sulphur"],
        "Sulfur",
        "Active",
        "An old acne and dandruff ingredient. It smells, and it can be drying.",
        "Dryness is the usual short-term effect.",
        "Can help some acne and seborrhoeic dermatitis. Easy to overdo on sensitive skin.",
        [H("acne", "Sulfur can help some acne, especially if benzoyl peroxide is too harsh."),
         H("dandruff", "Sulfur is sometimes used for flaky scalp conditions."),
         C("sensitive", "It is drying."),
         C("eczema", "Can hurt cracked eczema.")],
    ),
    ing(
        "glutathione",
        ["glutathione"],
        "Glutathione",
        "Active",
        "An antioxidant. COSMIX does not score skin whitening as a benefit. Evidence that topical glutathione changes skin colour is weak.",
        "Unlikely to do anything visible in the short term.",
        "Do not buy this to lighten your skin. If it is only an antioxidant on a normal list, it is not a hazard signal by itself.",
        [],
    ),
    ing(
        "snail",
        ["snail secretion filtrate", "snail mucin", "snail filtrate"],
        "Snail secretion filtrate",
        "Active",
        "A popular moisturising filtrate. Evidence for special healing claims is limited. Dust-mite allergy is a rare crossover concern.",
        "Usually feels hydrating. Stop if you itch.",
        "A humectant trend. Not a treatment for scars or melasma.",
        [H("dry", "Often moisturising."),
         C("sensitive", "Stop if you develop an itchy rash. Rarely, people with severe dust-mite allergy react.")],
    ),
    ing(
        "formaldehyde",
        ["formaldehyde", "formalin", "methylene glycol"],
        "Formaldehyde",
        "Preservative",
        "A harsh preservative and a known skin sensitiser. It does not belong in a leave-on cosmetic you buy for your face.",
        "It can irritate quickly and can start an allergy that then reacts to very small amounts.",
        "Once allergic, people react to formaldehyde-releasing preservatives in other products too. Avoid.",
        [A("Formaldehyde is a sensitiser. Do not use this on skin as a cosmetic ingredient.")],
    ),
    ing(
        "dmdm",
        ["dmdm hydantoin"],
        "DMDM hydantoin",
        "Preservative",
        "A preservative that releases small amounts of formaldehyde.",
        "Many people never notice it. People with a formaldehyde allergy will.",
        "A common reason a 'simple' product keeps causing eyelid or face rashes. Prefer formulas without formaldehyde releasers if your skin is reactive.",
        [C("always", "This preservative releases formaldehyde. Fine for some people, a problem if you react to preservatives."),
         V("sensitive", "If your skin is sensitive or you get rashes from many products, do not pick a formaldehyde releaser."),
         V("eczema", "Formaldehyde releasers are a poor choice in eczema.")],
    ),
    ing(
        "quaternium15",
        ["quaternium-15"],
        "Quaternium-15",
        "Preservative",
        "A formaldehyde-releasing preservative and a well-known allergen.",
        "Can be the hidden cause of a rash that starts days after use.",
        "Best avoided, especially on leave-on products and on eczema.",
        [V("leave_on", "Quaternium-15 is a formaldehyde releaser. Do not leave it on the skin."),
         V("eczema", "A poor preservative choice in eczema."),
         V("sensitive", "A known allergen for reactive skin."),
         C("always", "This preservative releases formaldehyde.")],
    ),
    ing(
        "imidazolidinyl_urea",
        ["imidazolidinyl urea"],
        "Imidazolidinyl urea",
        "Preservative",
        "A formaldehyde-releasing preservative.",
        "Often tolerated until someone becomes allergic, then small amounts rash.",
        "If you have sensitive skin or eczema, choose a different preservative system.",
        [C("always", "This is a formaldehyde releaser."),
         V("sensitive", "Skip this if your skin reacts easily."),
         V("eczema", "A poor match for eczema.")],
    ),
    ing(
        "diazolidinyl_urea",
        ["diazolidinyl urea"],
        "Diazolidinyl urea",
        "Preservative",
        "A formaldehyde-releasing preservative, similar problem to imidazolidinyl urea.",
        "Rashes from it are often delayed, so people blame the wrong product.",
        "Avoid on sensitive skin and eczema.",
        [C("always", "This is a formaldehyde releaser."),
         V("sensitive", "Skip this if your skin reacts easily."),
         V("eczema", "A poor match for eczema.")],
    ),
    ing(
        "bronopol",
        ["2-bromo-2-nitropropane-1,3-diol", "bronopol"],
        "Bronopol",
        "Preservative",
        "A preservative that can release formaldehyde and can irritate.",
        "More of a problem in leave-on products than in a quick wash.",
        "Not a modern first choice for sensitive skin.",
        [C("leave_on", "Bronopol on a leave-on product is an unnecessary irritant risk."),
         C("sensitive", "Can irritate sensitive skin."),
         C("eczema", "A poor match for eczema.")],
    ),
    ing(
        "mit",
        ["methylisothiazolinone"],
        "Methylisothiazolinone",
        "Preservative",
        "A preservative that caused a wave of cosmetic allergies. Leave-on use is heavily restricted in the EU.",
        "The rash can appear days later and look like eczema around the eyes and hands.",
        "Once you are allergic, tiny amounts keep the rash going. Rinse-off is lower risk than leave-on, and it is still not zero.",
        [V("leave_on", "Methylisothiazolinone should not be in a leave-on cosmetic. Pick another product."),
         V("eczema", "This preservative is a well-known eczema trigger."),
         V("sensitive", "If your skin is sensitive, do not choose methylisothiazolinone."),
         C("always", "A high-profile allergy preservative, even in some wash-off products.")],
    ),
    ing(
        "mci",
        ["methylchloroisothiazolinone"],
        "Methylchloroisothiazolinone",
        "Preservative",
        "Paired with methylisothiazolinone. A strong sensitiser.",
        "Can cause a delayed rash that people do not connect to the product.",
        "Avoid in leave-on products and if you have eczema.",
        [V("leave_on", "Do not leave methylchloroisothiazolinone on the skin."),
         V("eczema", "A well-known eczema trigger."),
         V("sensitive", "A poor choice for sensitive skin."),
         C("always", "A strong preservative allergen.")],
    ),
    ing(
        "mdbgn",
        ["methyldibromo glutaronitrile", "methyldibromoglutaronitrile"],
        "Methyldibromo glutaronitrile",
        "Preservative",
        "A preservative with a high allergy rate. Banned in EU leave-on cosmetics and restricted further after that.",
        "A delayed rash is the usual pattern.",
        "Do not buy a leave-on product that still lists it.",
        [V("leave_on", "This preservative should not be in a leave-on product."),
         V("eczema", "High allergy risk in eczema."),
         V("sensitive", "High allergy risk on sensitive skin."),
         C("always", "A preservative with a bad allergy record.")],
    ),
    ing(
        "triclosan",
        ["triclosan"],
        "Triclosan",
        "Preservative",
        "An antibacterial that does not make a cosmetic cleaner in a useful way for healthy skin, and it has safety restrictions.",
        "Can irritate.",
        "Skip it. Washing with a normal cleanser is enough. It is not a treatment for acne by itself.",
        [C("always", "Triclosan is an unnecessary antibacterial in a cosmetic. Prefer a product without it."),
         V("child", "Do not use triclosan products on a young child."),
         C("pregnancy", "Prefer to avoid triclosan in pregnancy.")],
    ),
    ing(
        "triclocarban",
        ["triclocarban"],
        "Triclocarban",
        "Preservative",
        "Another old antibacterial used in bar soaps. Not needed for ordinary washing.",
        "Can irritate.",
        "No meaningful benefit over plain soap for a healthy person.",
        [C("always", "Triclocarban is an unnecessary antibacterial in a wash product."),
         C("pregnancy", "Prefer to avoid it in pregnancy.")],
    ),
    ing(
        "phenoxyethanol",
        ["phenoxyethanol"],
        "Phenoxyethanol",
        "Preservative",
        "A very common preservative. It is not the same chemical as drying alcohol, even though the name contains 'ethanol'.",
        "Most people notice nothing. A few get sting on cracked skin.",
        "An ordinary preservative at normal cosmetic levels. The allergy rate is far lower than for methylisothiazolinone.",
        [C("eczema", "Usually tolerated, but cracked eczema can sting. Stop if this product is the one that burns."),
         C("sensitive", "Possible mild sting. It is still one of the more acceptable preservatives.")],
    ),
    ing(
        "parabens",
        ["paraben", "methylparaben", "ethylparaben", "propylparaben", "butylparaben", "isobutylparaben"],
        "Parabens",
        "Preservative",
        "Preservatives that stop microbes growing in the jar. A common internet claim links them to cancer. That claim is not established for cosmetic use.",
        "At normal levels they rarely irritate. A true paraben allergy is less common than a fragrance allergy, and it is real if you have it.",
        "If you are not allergic, parabens are not a reason to reject a product. If you are allergic, avoid the whole family.",
        [V("paraben_allergy", "You flagged a paraben allergy. Do not use this product."),
         C("eczema", "Parabens are an uncommon but real allergy. If every cream flares you, this family is worth discussing with a dermatologist.")],
    ),
    ing(
        "sodium_benzoate",
        ["sodium benzoate"],
        "Sodium benzoate",
        "Preservative",
        "A common preservative, also used in food.",
        "Usually uneventful on skin.",
        "Ordinary preservative. Not a signal of a harsh product.",
        [],
    ),
    ing(
        "potassium_sorbate",
        ["potassium sorbate", "sorbic acid"],
        "Potassium sorbate",
        "Preservative",
        "A common mild preservative.",
        "Can sting cracked skin occasionally.",
        "Ordinary and generally acceptable.",
        [C("sensitive", "Occasional sting on very reactive skin. Not a high-alert preservative.")],
    ),
    ing(
        "bht",
        ["bht", "butylated hydroxytoluene"],
        "BHT",
        "Preservative",
        "An antioxidant that keeps oils in the formula from going off. Not the same as a formaldehyde releaser.",
        "A few people react. Most do not.",
        "A minor ingredient. Worth avoiding only if you already know you react to it.",
        [C("sensitive", "Possible allergy. Low on the list of usual triggers compared with fragrance.")],
    ),
    ing(
        "chlorhexidine",
        ["chlorhexidine", "chlorhexidine digluconate"],
        "Chlorhexidine",
        "Preservative",
        "An antiseptic. Rarely, it causes severe allergic reactions, especially on broken skin and in medical settings.",
        "Do not put an antiseptic wash on the face every day to 'stay clean'.",
        "Useful as a medical antiseptic when a clinician wants it. As a daily cosmetic it is unnecessary, and allergy can be serious.",
        [C("always", "Chlorhexidine is a medical antiseptic, not a daily cosmetic cleanser."),
         V("eczema", "Do not use chlorhexidine on widespread eczema unless a doctor told you to."),
         C("barrier", "Broken skin plus chlorhexidine needs medical advice, not a shop routine.")],
    ),
    ing(
        "sls",
        ["sodium lauryl sulfate", "sodium lauryl sulphate"],
        "Sodium lauryl sulfate",
        "Cleanser",
        "A strong cleanser. It removes oil well and it is drying. It is not a steroid, a toxin ban-list item, or the same as a gentle baby wash.",
        "In a face wash, skin can feel tight for hours. In a leave-on cream, it is more likely to irritate.",
        "Fine for many scalps and bodies if you moisturise after. A poor choice to leave on sensitive or eczema-prone faces.",
        [C("leave_on", "Sodium lauryl sulfate in a leave-on product is an odd, irritating choice."),
         C("sensitive", "This cleanser is harsher than your skin type wants."),
         C("eczema", "A common irritant in eczema. Prefer a gentler cleanser."),
         C("rosacea", "Harsh cleansers worsen rosacea."),
         C("barrier", "Strong sulfate cleansers slow barrier recovery."),
         C("dry", "Expect tightness. Use a moisturiser after washing and do not leave it on.")],
    ),
    ing(
        "sles",
        ["sodium laureth sulfate", "sodium laureth sulphate"],
        "Sodium laureth sulfate",
        "Cleanser",
        "A common shampoo and body-wash cleanser. Milder than sodium lauryl sulfate, and still able to dry skin.",
        "Can feel tight if you use it on the face.",
        "Normal in rinse-off hair products. Not a great leave-on face ingredient.",
        [C("leave_on", "This belongs in a wash, not in a leave-on face product."),
         C("eczema", "Can still flare eczema. Rinse well and moisturise."),
         C("sensitive", "May be too strong for a sensitive face."),
         C("rosacea", "Can worsen tightness and flushing.")],
    ),
    ing(
        "capb",
        ["cocamidopropyl betaine"],
        "Cocamidopropyl betaine",
        "Cleanser",
        "A gentler cleanser made with coconut chemistry. A known, if uncommon, allergen.",
        "Usually milder than sulfates. Itch means you might be one of the allergic minority.",
        "A standard wash ingredient. Allergy, when it happens, tends to be from impurities and shows up as eyelid or face itch.",
        [C("sensitive", "Usually gentle, but it is a recognised allergen. Stop if you itch."),
         C("eczema", "Possible allergen in people who react to many washes."),
         V("coconut_allergy", "This is coconut-derived. Avoid it if coconut itself gives you a reaction.")],
    ),
    ing(
        "mild_glucoside",
        ["coco glucoside", "cocoglucoside", "lauryl glucoside", "decyl glucoside"],
        "Mild glucoside cleanser",
        "Cleanser",
        "A gentler family of cleansers. Decyl glucoside is also a less common allergen.",
        "Usually comfortable in a wash.",
        "A better cleanser direction for dry or eczema-prone skin than a strong sulfate.",
        [H("dry", "Gentler wash ingredients suit dry skin better than strong sulfates."),
         H("eczema", "Often a better cleanser family in eczema, unless you already react to it."),
         C("sensitive", "Decyl glucoside can rarely cause allergy. Stop if a 'gentle' wash itches.")],
    ),
    ing(
        "sci",
        ["sodium cocoyl isethionate"],
        "Sodium cocoyl isethionate",
        "Cleanser",
        "A mild solid-cleanser ingredient used in syndet bars. It is not sodium hydroxide.",
        "Usually gentle in a rinse-off bar.",
        "A reasonable cleanser for people who find soap harsh.",
        [H("sensitive", "Often milder than soap or sodium lauryl sulfate."),
         V("coconut_allergy", "Coconut-derived. Skip if you react to coconut.")],
    ),
    ing(
        "fragrance",
        ["parfum", "perfume", "fragrance", "aroma"],
        "Fragrance",
        "Fragrance",
        "A mix of scent chemicals. The label usually does not say which ones. This is the most useful line to notice if your skin reacts and you do not know why.",
        "Sting, itch, or a rash can show up within minutes or within a few days.",
        "Repeated use is how new cosmetic allergies start, especially on eyelids and necks. Unscented is a better long-term bet if you have sensitive skin, eczema, or a known fragrance allergy.",
        [V("fragrance_allergy", "You flagged a fragrance allergy. Parfum is an undeclared mix of scent chemicals."),
         C("sensitive", "Fragrance is one of the top causes of irritation on sensitive skin."),
         C("eczema", "Fragrance often flares eczema."),
         C("rosacea", "Scented products often worsen burning and flushing."),
         C("barrier", "A damaged barrier lets fragrance irritate more."),
         C("child", "Skip added fragrance on a young child's leave-on products.")],
    ),
    ing(
        "limonene",
        ["limonene", "citrus limon", "citrus sinensis", "citrus paradisi", "lemon peel oil", "orange peel oil"],
        "Limonene",
        "Fragrance",
        "A citrus scent chemical that must be listed when it is above a small amount. Oxidised citrus oils also make sun reactions more likely.",
        "Can itch if you are scent-allergic. Citrus oils on skin plus sun can cause a burn-like rash.",
        "A common 'natural' allergen. Listing it is a warning for allergic people, not a claim that every person must avoid citrus.",
        [V("fragrance_allergy", "Limonene is a fragrance allergen. Avoid it with a fragrance allergy."),
         C("sensitive", "A common scent allergen."),
         C("eczema", "Citrus scent chemicals often flare eczema."),
         C("leave_on", "Citrus oils in leave-on products can cause a sun reaction. Night use is safer, and sunscreen still matters.")],
    ),
    ing(
        "linalool",
        ["linalool"],
        "Linalool",
        "Fragrance",
        "A floral scent allergen. Common in products sold as natural.",
        "Nothing for many people. A delayed rash for people who are allergic.",
        "One of the fragrance chemicals most often positive on allergy patch tests.",
        [V("fragrance_allergy", "Linalool is a fragrance allergen."),
         C("sensitive", "A common scent allergen."),
         C("eczema", "Often a poor match for eczema.")],
    ),
    ing(
        "citronellol",
        ["citronellol"],
        "Citronellol",
        "Fragrance",
        "A rose-like scent allergen.",
        "Relevant if you react to scented products.",
        "Another listed fragrance allergen, not an automatic danger for every person.",
        [V("fragrance_allergy", "Citronellol is a fragrance allergen."),
         C("sensitive", "Possible scent allergen."),
         C("eczema", "Skip extra scent allergens in eczema.")],
    ),
    ing(
        "geraniol",
        ["geraniol"],
        "Geraniol",
        "Fragrance",
        "A rose-scent allergen.",
        "Can be the reason a 'rose' product itches.",
        "Listed so allergic people can avoid it.",
        [V("fragrance_allergy", "Geraniol is a fragrance allergen."),
         C("sensitive", "Possible scent allergen."),
         C("eczema", "Skip in eczema if scent is already a trigger.")],
    ),
    ing(
        "eugenol",
        ["eugenol"],
        "Eugenol",
        "Fragrance",
        "A spicy scent allergen found in clove-type smells.",
        "Can burn in higher amounts.",
        "A classic fragrance allergen.",
        [V("fragrance_allergy", "Eugenol is a fragrance allergen."),
         C("sensitive", "Can irritate sensitive skin."),
         C("eczema", "A poor match for eczema.")],
    ),
    ing(
        "citral",
        ["citral"],
        "Citral",
        "Fragrance",
        "A lemon-scent allergen.",
        "Can itch or cause a sun reaction when citrus oils sit on skin.",
        "Avoid if fragrance-allergic.",
        [V("fragrance_allergy", "Citral is a fragrance allergen."),
         C("sensitive", "A citrus allergen and irritant."),
         C("leave_on", "Citrus-type allergens on leave-on skin can react in the sun.")],
    ),
    ing(
        "cinnamal",
        ["cinnamal", "cinnamaldehyde"],
        "Cinnamal",
        "Fragrance",
        "A cinnamon scent allergen. One of the stronger ones.",
        "Can itch or burn.",
        "Worth avoiding on sensitive skin even before a formal allergy test.",
        [V("fragrance_allergy", "Cinnamal is a strong fragrance allergen."),
         C("sensitive", "Cinnamon-type scent is a strong irritant."),
         C("eczema", "A poor match for eczema."),
         C("always", "Cinnamal is one of the harsher scent allergens.")],
    ),
    ing(
        "hexyl_cinnamal",
        ["hexyl cinnamal"],
        "Hexyl cinnamal",
        "Fragrance",
        "A milder cinnamon-related scent allergen.",
        "Usually only relevant if scents bother you.",
        "Listed for allergy avoidance.",
        [V("fragrance_allergy", "Hexyl cinnamal is a fragrance allergen."),
         C("sensitive", "Possible scent allergen."),
         C("eczema", "Skip extra scent if eczema is scent-triggered.")],
    ),
    ing(
        "coumarin",
        ["coumarin"],
        "Coumarin",
        "Fragrance",
        "A sweet scent allergen, like new-mown hay or tonka.",
        "Relevant mainly if you have a fragrance allergy.",
        "A listed allergen, not a reason for every person to panic.",
        [V("fragrance_allergy", "Coumarin is a fragrance allergen."),
         C("sensitive", "Possible scent allergen.")],
    ),
    ing(
        "benzyl_alcohol",
        ["benzyl alcohol"],
        "Benzyl alcohol",
        "Fragrance",
        "Used as a preservative and as a scent component. It is not the same as the drying alcohol high up a toner list.",
        "Can sting cracked skin and can be a fragrance allergen.",
        "Acceptable for many people at preservative levels. Avoid if fragrance-allergic.",
        [V("fragrance_allergy", "Benzyl alcohol is a fragrance allergen as well as a preservative."),
         C("sensitive", "Can sting sensitive or cracked skin."),
         C("eczema", "Possible irritant in eczema.")],
    ),
    ing(
        "benzyl_salicylate",
        ["benzyl salicylate"],
        "Benzyl salicylate",
        "Fragrance",
        "A scent allergen that is also in the salicylate family.",
        "Relevant if either fragrance or aspirin-type allergy is your problem.",
        "Avoid in both of those cases.",
        [V("fragrance_allergy", "Benzyl salicylate is a fragrance allergen."),
         V("salicylate_allergy", "This is also a salicylate. Avoid it with an aspirin or salicylate allergy.")],
    ),
    ing(
        "menthol",
        ["menthol"],
        "Menthol",
        "Fragrance",
        "Creates a cool feeling. That feeling is a nerve trick, not healing.",
        "Can burn, especially on broken or eczema-prone skin, even while it feels 'medicated'.",
        "No long-term benefit for acne, pigment, or aging. It trains people to think sting means the product works.",
        [C("sensitive", "Menthol is an irritant dressed up as a cooling sensation."),
         C("eczema", "Menthol often burns eczema."),
         C("rosacea", "Cooling agents often worsen rosacea."),
         C("barrier", "Do not put menthol on a damaged barrier.")],
    ),
    ing(
        "peppermint",
        ["peppermint oil", "mentha piperita", "peppermint"],
        "Peppermint oil",
        "Fragrance",
        "An essential oil that cools and irritates. Poor choice on the face.",
        "Burning is common on facial skin.",
        "Not a treatment. Repeated use can become an allergy.",
        [V("fragrance_allergy", "Peppermint oil is a scent ingredient."),
         C("sensitive", "Peppermint oil is too harsh for sensitive facial skin."),
         C("eczema", "Often flares eczema."),
         C("rosacea", "Often worsens burning."),
         C("child", "Do not use peppermint oil on a young child's face.")],
    ),
    ing(
        "camphor",
        ["camphor"],
        "Camphor",
        "Fragrance",
        "A cooling irritant. The tingle is not evidence that acne or pigment is being treated.",
        "Can burn.",
        "No good reason to have it in a modern face cream.",
        [C("always", "Camphor is a cooling irritant. It is not doing medical work in a cosmetic."),
         V("child", "Do not use camphor products on a young child."),
         C("eczema", "Burns eczema."),
         C("sensitive", "Too harsh for sensitive skin.")],
    ),
    ing(
        "alcohol_denat",
        ["alcohol denat", "sd alcohol", "sd alcohol 40", "sd alcohol 40-b", "denatured alcohol", "isopropyl alcohol", "isopropanol", "ethanol", "alcohol"],
        "Drying alcohol",
        "Base",
        "The light, evaporating alcohol. It is not cetyl alcohol or cetearyl alcohol, which are waxy and non-drying.",
        "High on a leave-on list, it can sting and strip water from the skin within minutes.",
        "Daily use of a high-alcohol toner can worsen dryness, eczema, and the look of oiliness later, because the skin dries out. Lower down a list, the amount is smaller.",
        [C("high_on_list", "Drying alcohol is near the top of a leave-on list, so the amount is likely to matter. It can sting and dry the skin."),
         C("sensitive", "Drying alcohol is a poor match for sensitive skin."),
         C("eczema", "It commonly stings and dries eczema."),
         C("rosacea", "Alcohol toners often worsen flushing."),
         C("barrier", "Drying alcohol slows barrier recovery."),
         C("dry", "It works against dry skin if it is a major ingredient.")],
    ),
    ing(
        "fatty_alcohol",
        ["cetyl alcohol", "cetearyl alcohol", "stearyl alcohol", "behenyl alcohol", "myristyl alcohol"],
        "Fatty alcohols",
        "Base",
        "Waxy alcohols used as thickeners. They are not the same as the drying alcohol in a toner, and they do not dry the skin.",
        "Usually feel conditioning.",
        "Normal, useful base ingredients in creams and conditioners.",
        [],
    ),
    ing(
        "water",
        ["water", "aqua", "eau", "purified water", "deionized water", "aqua water"],
        "Water",
        "Base",
        "The main liquid in most formulas. Seeing it first is normal, not a sign of a weak or fake product.",
        "No effect by itself.",
        "No long-term meaning. The ingredients after water are the ones to read.",
        [],
    ),
    ing(
        "glycerin",
        ["glycerin", "glycerine", "glycerol"],
        "Glycerin",
        "Base",
        "A very common moisture-binder. One of the most useful boring ingredients in skincare.",
        "Helps skin feel less tight. Should not sting.",
        "A good long-term moisturising ingredient, especially with a cream over it if your air is dry.",
        [H("dry", "Glycerin is a sound ingredient for dry skin."),
         H("barrier", "Useful while a barrier is recovering."),
         H("eczema", "Glycerin is a standard helper in eczema moisturisers, if the rest of the formula is calm.")],
    ),
    ing(
        "dimethicone",
        ["dimethicone", "dimethiconol", "phenyl trimethicone"],
        "Dimethicone",
        "Base",
        "A silicone that makes skin or hair feel smooth. It sits on top. It is not a treatment, and it is not automatically pore-clogging.",
        "The smooth feel is immediate and cosmetic.",
        "Can protect a raw barrier from water loss. It will not treat acne or pigment. If you specifically react to silicones, avoid it.",
        [H("barrier", "Silicone can shield a damaged barrier while it heals."),
         H("dry", "Helps seal water in.")],
    ),
    ing(
        "cyclopentasiloxane",
        ["cyclopentasiloxane", "cyclohexasiloxane", "cyclomethicone"],
        "Volatile silicone",
        "Base",
        "A light silicone that mostly evaporates. It makes products feel dry and silky.",
        "Usually no sting.",
        "A texture ingredient, not a treatment. Skin safety is generally fine. The environmental debate about some silicones is separate from a rash risk.",
        [],
    ),
    ing(
        "propylene_glycol",
        ["propylene glycol", "propanediol"],
        "Propylene glycol",
        "Base",
        "A common solvent and moisture-binder. It is not a banned toxin. A minority of people with very sensitive skin do react to it.",
        "Usually nothing. Occasional sting on cracked skin.",
        "Normal cosmetic ingredient. Avoid only if you already know you react.",
        [C("sensitive", "A possible irritant if your skin reacts to many creams. Not a reason for most people to refuse a product."),
         C("eczema", "Can sting cracked eczema. Patch test if your skin is very reactive.")],
    ),
    ing(
        "butylene_glycol",
        ["butylene glycol"],
        "Butylene glycol",
        "Base",
        "A common moisture-binder, related in use to propylene glycol, and usually a bit gentler.",
        "Usually nothing.",
        "Ordinary base. Not a red flag.",
        [C("sensitive", "Uncommon irritant. Stop only if this formula stings and you have narrowed it down.")],
    ),
    ing(
        "pentylene_glycol",
        ["pentylene glycol"],
        "Pentylene glycol",
        "Base",
        "A moisturising solvent often used in modern serums. Generally well tolerated.",
        "Usually nothing.",
        "Ordinary supporting ingredient.",
        [],
    ),
    ing(
        "hexylenediol",
        ["1,2-hexanediol", "hexanediol", "caprylyl glycol", "ethylhexylglycerin"],
        "Modern preservative boosters",
        "Preservative",
        "Ingredients such as 1,2-hexanediol, caprylyl glycol, and ethylhexylglycerin help preservatives work. They are common in 'clean' formulas.",
        "Usually well tolerated. Can sting a minority of people.",
        "A normal modern preservative approach, not a hidden steroid or formaldehyde releaser.",
        [C("sensitive", "Can occasionally sting. Still a reasonable preservative system.")],
    ),
    ing(
        "isopropyl_myristate",
        ["isopropyl myristate"],
        "Isopropyl myristate",
        "Base",
        "A light oily ingredient. Some acne-prone people find it clogs pores. It is not a banned substance.",
        "Feels silky. Breakouts, if they happen, show up over days to a few weeks.",
        "Fine for many dry skins. A weaker choice if you clog easily and this is a face product.",
        [C("acne", "Some acne-prone people find isopropyl myristate clogs pores. It is not guaranteed to, and it is worth watching."),
         H("dry", "It feels softening on dry skin that is not acne-prone.")],
    ),
    ing(
        "mineral_oil",
        ["mineral oil", "paraffinum liquidum", "paraflinum liquidum", "mineral oilatum"],
        "Mineral oil",
        "Base",
        "A highly refined oil used to seal water into skin. Cosmetic mineral oil is not industrial crude oil.",
        "Sits on the skin and reduces dryness. Should not sting.",
        "Very effective for dryness and barrier protection. It is not 'dirty' in the way marketing claims. A minority of acne-prone people dislike heavy oils.",
        [H("dry", "Mineral oil is an effective seal over damp, dry skin."),
         H("eczema", "Plain mineral oil or petrolatum is often kinder than a scented cream in eczema."),
         H("barrier", "A proven way to reduce water loss."),
         C("acne", "Heavy oils bother some acne-prone people. Mineral oil is less clogging than its reputation, but watch your own skin.")],
    ),
    ing(
        "petrolatum",
        ["petrolatum", "petroleum jelly", "white petrolatum"],
        "Petrolatum",
        "Base",
        "The ingredient in plain petroleum jelly. One of the best-tested ways to stop water leaving the skin.",
        "Immediate protection. It will not treat pigment or acne.",
        "Excellent barrier ointment if the formula is plain. Acne-prone faces sometimes hate the feel and clog. Fragrance in a jelly is the usual real problem, not petrolatum itself.",
        [H("dry", "Petrolatum is excellent for very dry skin."),
         H("barrier", "A standard barrier protectant."),
         H("eczema", "Plain petrolatum is a core eczema-care moisturiser."),
         C("acne", "The feel is heavy. Some acne-prone people clog with ointments on the whole face.")],
    ),
    ing(
        "shea",
        ["butyrospermum parkii", "shea butter", "shea"],
        "Shea butter",
        "Base",
        "A rich plant butter. Useful for dry skin. Heavy on some acne-prone faces.",
        "Softens quickly.",
        "Good body and dry-face ingredient. If you clog easily, do not assume a thick shea cream belongs on the whole face.",
        [H("dry", "Shea is a real moisturiser for dry skin."),
         C("acne", "Rich butters can clog some acne-prone faces."),
         C("nut_allergy", "Shea comes from a tree nut. Most people with a peanut allergy tolerate shea. Skip it if you already react to shea, or if your allergist told you to avoid it.")],
    ),
    ing(
        "coconut_oil",
        ["cocos nucifera", "coconut oil", "coconut butter"],
        "Coconut oil",
        "Base",
        "A heavy oil. Good on many bodies and scalps, and a frequent clog on acne-prone faces. Coconut allergy is not the same as peanut allergy.",
        "Feels rich immediately. Clogs, if they happen, appear over the next couple of weeks.",
        "Poor default for facial acne. Fine for many dry body routines.",
        [V("coconut_allergy", "You flagged a coconut allergy."),
         C("acne", "Coconut oil clogs a lot of acne-prone faces. Hair and body are a different story."),
         H("dry", "Useful on dry body skin if your face is not the area that clogs.")],
    ),
    ing(
        "olive_oil",
        ["olea europaea", "olive oil", "olea europea"],
        "Olive oil",
        "Base",
        "A kitchen oil that is not a great face moisturiser. It can hurt the barrier of some skin and it can clog.",
        "Feels oily. Can sting if the barrier is already weak.",
        "There are better moisturisers than olive oil for the face, especially in eczema.",
        [C("acne", "Olive oil can clog acne-prone skin."),
         C("eczema", "Olive oil can worsen the skin barrier in some eczema. Petrolatum or glycerin creams are usually safer."),
         C("sensitive", "Not as gentle as its natural image.")],
    ),
    ing(
        "castor",
        ["ricinus communis", "castor oil", "hydrogenated castor oil"],
        "Castor oil",
        "Base",
        "A thick oil used in lip products and some hair oils. PEG-40 hydrogenated castor oil is a different, watery solubiliser.",
        "Usually a texture ingredient.",
        "Normal in lipsticks. Not a hair-growth treatment.",
        [],
    ),
    ing(
        "peg40_castor",
        ["peg-40 hydrogenated castor oil"],
        "PEG-40 hydrogenated castor oil",
        "Base",
        "A solubiliser that helps mix fragrance or oils into water. Not the same as rubbing castor oil on your face.",
        "Usually unnoticed.",
        "A normal base ingredient in watery serums and mists.",
        [],
    ),
    ing(
        "lanolin",
        ["lanolin", "lanolin alcohol", "wool wax", "adeps lanae"],
        "Lanolin",
        "Base",
        "An ointment from sheep's wool. Excellent for dry lips and dry skin, and a classic allergy for a minority.",
        "Softens fast. Itch or a rash means you may be in the allergic minority.",
        "Very useful if you tolerate it. Avoid if you already know lanolin rashes you.",
        [V("lanolin_allergy", "You flagged a lanolin allergy."),
         H("dry", "Lanolin is highly effective for dry skin and lips if you are not allergic."),
         C("sensitive", "Possible allergen. Stop if you itch."),
         C("eczema", "Some people with eczema are allergic to lanolin. If a plain ointment helps and a lanolin one hurts, this is a suspect.")],
    ),
    ing(
        "aloe",
        ["aloe barbadensis", "aloe vera", "aloe leaf juice", "aloe"],
        "Aloe",
        "Base",
        "A plant juice used for a cooling feel. The soothing reputation is bigger than the evidence, and some people become allergic.",
        "Feels cool. That is not the same as healing a burn or a disease.",
        "Fine as a light extra if you tolerate it. Not a substitute for a proper moisturiser or for medical burn care.",
        [H("sensitive", "Often calming, and sometimes the allergen. Stop if you itch."),
         C("eczema", "Plant juices can become a new allergy in eczema.")],
    ),
    ing(
        "squalane",
        ["squalane", "squalene"],
        "Squalane",
        "Base",
        "A light oil similar to a lipid skin already makes. Usually well tolerated, including by some acne-prone people.",
        "Softens without a heavy shine for many people.",
        "A reasonable long-term moisturising oil. Squalene (with an e) oxidises more easily than squalane (with an a).",
        [H("dry", "A light moisturising oil."),
         H("barrier", "A reasonable barrier-support oil."),
         H("sensitive", "Often tolerated when heavier oils are not.")],
    ),
    ing(
        "caprylic",
        ["caprylic capric triglyceride"],
        "Caprylic/capric triglyceride",
        "Base",
        "A light, coconut-derived emollient. Usually not as heavy as coconut oil itself.",
        "Silky feel. Uncommon to clog compared with coconut oil, but not impossible.",
        "A normal modern moisturiser base.",
        [H("dry", "A light moisturising ingredient."),
         C("coconut_allergy", "This is coconut-derived. Avoid it if you react to coconut.")],
    ),
    ing(
        "stearic",
        ["stearic acid", "glyceryl stearate", "glyceryl stearate se", "glyceryl distearate", "peg 100 stearate"],
        "Stearic acid and glyceryl stearate",
        "Base",
        "Waxy emulsifiers that give creams and soap washes their body. Not strong actives.",
        "No treatment effect.",
        "Normal cream and wash architecture. Glyceryl distearate is the same family, not a separate drug.",
        [],
    ),
    ing(
        "soap_fatty_acid",
        ["myristic acid", "palmitic acid"],
        "Myristic and palmitic acid",
        "Cleanser",
        "Fatty acids that react with an alkali to become soap. In a finished face wash they are part of the lather, not loose acids left on the skin.",
        "They help the wash foam. A finished soap should not sting just because these names are listed.",
        "Normal soap-base ingredients. A harsh wash can still leave skin tight. That is the finished soap, not these two names alone.",
        [],
    ),
    ing(
        "lauric_acid",
        ["lauric acid"],
        "Lauric acid",
        "Cleanser",
        "A fatty acid that makes soap lather more. It cleans harder than the longer soap fatty acids. It is not the coconut protein that causes a coconut allergy.",
        "In a rinse-off wash the lather can feel squeaky. Rinse it off.",
        "A bubbly soap base. Fine for many oily faces. Dry, eczematous, or barrier-damaged skin often does better with a cream cleanser.",
        [C("dry", "Lauric-rich soap can leave dry skin tighter. Moisturise after, or pick a gentler wash."),
         C("eczema", "This kind of soap lather can sting cracked eczema."),
         C("barrier", "A strong soap base can slow a damaged barrier. A cream cleanser is usually kinder.")],
    ),
    ing(
        "potassium_hydroxide",
        ["potassium hydroxide"],
        "Potassium hydroxide",
        "Cleanser",
        "In a face wash this is the alkali that turns the fatty acids into soap. A finished ingredient list is not a bottle of lye.",
        "No separate burn from the name alone, once the soap has been made and rinsed.",
        "A normal soap-making step. If the finished wash feels tight or stingy, that is a harsh soap, not raw potassium hydroxide sitting on the face. This note is a shopping explanation, not a measurement of leftover alkali.",
        [C("dry", "Soap made this way can leave dry skin tight after rinsing."),
         C("eczema", "Soap can sting cracked eczema. Rinse well and moisturise."),
         C("barrier", "A soap wash can slow a damaged barrier."),
         C("high_on_list", "Potassium hydroxide is near the top of a leave-on list. That is not a normal trace for setting acidity.")],
    ),
    ing(
        "kaolin",
        ["kaolin", "kaolin clay"],
        "Kaolin",
        "Base",
        "A clay. In a wash it soaks up oil and then rinses away. It is not a bleach and it does not treat pigment.",
        "Oily skin can feel cleaner. Dry skin can feel tight.",
        "A reasonable clay for an oily wash. It will not clear acne or dark spots by itself.",
        [H("oily", "Kaolin can mop up oil in a rinse-off wash."),
         H("acne", "Clay in a wash can help an oily, spot-prone face. It is not a medicine."),
         C("dry", "Clay can leave dry skin tighter."),
         C("eczema", "Clay washes often dry eczema.")],
    ),
    ing(
        "peg14m",
        ["peg-14m"],
        "PEG-14M",
        "Base",
        "A thickener used to hold a wash together. It is not the same as PEG-40 hydrogenated castor oil, and it is not a treatment.",
        "No treatment effect.",
        "Normal wash architecture.",
        [],
    ),
    ing(
        "maltodextrin",
        ["maltodextrin"],
        "Maltodextrin",
        "Base",
        "A starch-like carrier. On a wash list it usually holds a plant extract in place. It is not vitamin C and it is not a treatment.",
        "No treatment effect at carrier levels.",
        "Normal supporting ingredient. Do not read it as an active.",
        [],
    ),
    ing(
        "citrus_extract",
        ["lemon fruit extract", "citrus junos fruit extract"],
        "Citrus fruit extract",
        "Fragrance",
        "A lemon or yuzu extract. It is not the same as ascorbic acid, and it is not proof the wash contains vitamin C. Scent allergens, when they are high enough to matter, are listed on their own.",
        "In a rinse-off wash the contact time is short. Leave-on citrus can itch or, in some people, cause a sun reaction.",
        "Do not buy the wash because the extract sounds like vitamin C. If you react to citrus scent, this is another reason to skip it.",
        [V("fragrance_allergy", "Citrus extracts can carry scent compounds. With a fragrance allergy, this is a reason to skip the product."),
         C("leave_on", "Citrus extract left on skin can cause a sun reaction in some people. Sunscreen still matters."),
         C("sensitive", "Citrus extracts can sting sensitive skin."),
         C("eczema", "Citrus extracts often flare eczema.")],
    ),
    ing(
        "carbomer",
        ["carbomer", "carbomer 940", "acrylate copolymer", "sodium polyacrylate"],
        "Carbomer and common thickeners",
        "Base",
        "Gels and thickeners. They decide the texture, not the treatment.",
        "No treatment effect.",
        "Normal and generally well tolerated.",
        [],
    ),
    ing(
        "xanthan",
        ["xanthan gum"],
        "Xanthan gum",
        "Base",
        "A thickener made by fermentation. Common and usually inert on skin.",
        "No treatment effect.",
        "Normal base ingredient.",
        [],
    ),
    ing(
        "edta",
        ["disodium edta", "tetrasodium edta", "trisodium edta"],
        "EDTA",
        "Base",
        "A stabiliser that stops metal ions from spoiling the formula. Used at tiny amounts.",
        "Not a treatment.",
        "Normal stabiliser. Not the same as a preservative allergen like methylisothiazolinone.",
        [],
    ),
    ing(
        "citric",
        ["citric acid"],
        "Citric acid",
        "Base",
        "Usually present in a tiny amount to set the product's acidity. That is not the same as an acid peel.",
        "No peel effect at adjuster levels.",
        "Normal pH adjuster. Do not read it as glycolic acid.",
        [],
    ),
    ing(
        "sodium_hydroxide",
        ["sodium hydroxide"],
        "Sodium hydroxide",
        "Base",
        "Used in tiny amounts to set acidity, then balanced by the acids in the formula. On a normal ingredient list this is not a drain cleaner sitting on your face.",
        "No special short-term effect at adjuster levels.",
        "Normal in many creams. A product that is only a strong lye solution would not look like a cosmetic ingredient list.",
        [],
    ),
    ing(
        "sodium_chloride",
        ["sodium chloride", "salt"],
        "Salt",
        "Base",
        "Used to thicken some washes. 'Salt' as a whole token is easy to over-read.",
        "Can sting cracked skin and can dry if the wash is harsh.",
        "Not a meaningful hazard by itself in a normal formula.",
        [C("eczema", "Salt in a wash can sting cracked eczema. Rinse well.")],
    ),
    ing(
        "witch_hazel",
        ["hamamelis virginiana", "witch hazel", "hamamelis"],
        "Witch hazel",
        "Base",
        "A plant water that feels tightening. Many toners also add drying alcohol, which is the part that stings.",
        "The tight feeling is not the same as smaller pores that last.",
        "Alcohol-free witch hazel is a mild astringent. It will not treat acne or pores in a lasting way, and it can dry eczema.",
        [C("dry", "Tightening toners work against dry skin."),
         C("eczema", "Can dry and sting eczema."),
         C("rosacea", "Astringents often worsen rosacea."),
         C("sensitive", "The tight feeling is irritation more often than treatment.")],
    ),
    ing(
        "talc",
        ["talc"],
        "Talc",
        "Base",
        "A powder. Cosmetic talc is supposed to be free of asbestos. The main practical risk of loose powder is breathing it in, not a rash on intact skin.",
        "A dry feel. Stop if you cough from a powder cloud.",
        "In a pressed product on intact skin, this is a normal filler. Do not use loose powder on broken skin, and keep powder out of children's lungs.",
        [C("child", "Keep loose powder away from a child's face so they do not breathe it."),
         C("barrier", "Do not pack powder into broken skin.")],
    ),
    ing(
        "mica",
        ["mica"],
        "Mica",
        "Base",
        "A shimmer mineral used in makeup. Not an irritant for most skin.",
        "Visual shimmer only.",
        "A colour ingredient, not a treatment.",
        [],
    ),
    ing(
        "titanium_dioxide",
        ["titanium dioxide", "ci 77891"],
        "Titanium dioxide",
        "UV filter",
        "A mineral sunscreen filter and a white pigment. It sits on the skin and blocks UV.",
        "Can leave a white cast, especially on deeper skin tones. Should not sting.",
        "A sound sunscreen filter if the formula is broad spectrum and you use enough of it. The white cast is a cosmetic problem, not a safety problem.",
        [H("sensitive", "Mineral filters are often easier for sensitive skin than chemical filters."),
         H("rosacea", "Often a kinder sunscreen direction in rosacea."),
         H("child", "Mineral sunscreens are a common choice for children who need sun protection."),
         C("acne", "Thick mineral sunscreens can feel heavy. The filter itself is not an acne treatment problem for most people.")],
    ),
    ing(
        "zinc_oxide",
        ["zinc oxide"],
        "Zinc oxide",
        "UV filter",
        "A mineral sunscreen filter. Also used in nappy creams as a protectant. Different from zinc pca in serums.",
        "White cast is the usual complaint. Soothing for many reactive skins.",
        "One of the better sunscreen choices if chemical filters sting you. You still need enough product on the skin, reapplied.",
        [H("sensitive", "Zinc oxide is often the gentlest sunscreen filter."),
         H("rosacea", "A good sunscreen direction when chemical filters burn."),
         H("eczema", "Often tolerated in eczema when scented sunscreens are not."),
         H("child", "A standard mineral filter for children's sunscreen."),
         H("barrier", "Can protect raw skin from sun and friction.")],
    ),
    ing(
        "oxybenzone",
        ["oxybenzone", "benzophenone-3"],
        "Oxybenzone",
        "UV filter",
        "A chemical sunscreen filter. It protects against UV and it is one of the filters more often linked with sting and allergy.",
        "Sting or a rash in people who hate chemical sunscreens.",
        "Effective UV filter if you tolerate it. If you do not, zinc oxide and titanium dioxide are the other direction. Sunscreen as a category still matters.",
        [V("sunscreen_allergy", "You flagged a sunscreen-filter allergy. Oxybenzone is a chemical filter. Mineral filters are a different type."),
         C("sensitive", "One of the stingier chemical filters."),
         C("rosacea", "Chemical filters often burn rosacea."),
         C("child", "Many people prefer mineral filters for young children."),
         C("pregnancy", "Some people choose to avoid oxybenzone in pregnancy. Ask your doctor. Do not stop sun protection entirely.")],
    ),
    ing(
        "avobenzone",
        ["avobenzone", "butyl methoxydibenzoylmethane"],
        "Avobenzone",
        "UV filter",
        "A UVA filter. One of the more useful chemical filters, and it can still sting some people.",
        "Usually quiet. Can sting reactive skin.",
        "Good UVA protection when the formula stabilises it. Not an allergen for most people.",
        [V("sunscreen_allergy", "Avobenzone is a chemical sunscreen filter."),
         C("sensitive", "Possible sting."),
         C("rosacea", "Possible burn if chemical filters are already a problem for you.")],
    ),
    ing(
        "octinoxate",
        ["octinoxate", "ethylhexyl methoxycinnamate", "octyl methoxycinnamate"],
        "Octinoxate",
        "UV filter",
        "A UVB filter. Common, and more likely to sting than zinc oxide.",
        "Possible sting.",
        "Works as a UVB filter if tolerated.",
        [V("sunscreen_allergy", "Octinoxate is a chemical sunscreen filter."),
         C("sensitive", "More likely to sting than a mineral filter."),
         C("rosacea", "Can burn rosacea."),
         C("pregnancy", "If you are avoiding chemical filters in pregnancy, use a mineral sunscreen rather than skipping sun protection.")],
    ),
    ing(
        "homosalate",
        ["homosalate"],
        "Homosalate",
        "UV filter",
        "A chemical UVB filter.",
        "Possible sting if you react to sunscreens.",
        "Ordinary chemical filter. Switch to mineral if you react.",
        [V("sunscreen_allergy", "Homosalate is a chemical sunscreen filter."),
         C("sensitive", "Possible filter irritation.")],
    ),
    ing(
        "octocrylene",
        ["octocrylene"],
        "Octocrylene",
        "UV filter",
        "A chemical filter that also stabilises other filters. It is a more common photo-allergy suspect than zinc oxide.",
        "Rash in allergic people, sometimes only after sun.",
        "If sunscreens always rash you, this is one to mention to a dermatologist. Mineral filters are the alternative.",
        [V("sunscreen_allergy", "Octocrylene is a chemical filter and a fairly common sunscreen allergen."),
         C("sensitive", "A reasonable suspect if every chemical sunscreen burns."),
         C("eczema", "Can flare people who are already reactive.")],
    ),
    ing(
        "colophonium",
        ["colophonium", "rosin", "colophony"],
        "Colophonium (rosin)",
        "Fragrance",
        "A pine resin and a classic allergen in adhesives, and sometimes in cosmetics.",
        "Delayed rash if allergic.",
        "Avoid if you already react to plasters or pine resin.",
        [C("always", "Colophonium is a known allergen. Avoid it if plasters or pine resin already rash you."),
         V("fragrance_allergy", "Resin allergens often travel with fragrance allergy. Prefer to skip this."),
         V("eczema", "A poor choice in eczema if you have not patch tested.")],
    ),
    ing(
        "peanut",
        ["arachis hypogaea", "peanut oil", "peanut", "groundnut oil"],
        "Peanut oil",
        "Base",
        "Peanut oil. Relevant only if you have a peanut or groundnut allergy, in which case this is a stop.",
        "If you are allergic, do not patch test this for fun. Allergic reactions can be severe.",
        "Refined oils sometimes remove protein, but a cosmetic is the wrong place to experiment if you have a peanut allergy.",
        [V("nut_allergy", "You flagged a nut or peanut allergy. Do not use peanut oil. A cosmetic is the wrong place to test whether a refined oil is safe for you.")],
    ),
    ing(
        "ppd",
        ["p-phenylenediamine", "paraphenylenediamine", "ppd"],
        "p-Phenylenediamine",
        "Other",
        "The main allergen in permanent hair dye. Reactions can be severe, including swollen eyelids and face.",
        "A reaction often starts a day or two after dyeing, not always in the chair.",
        "Do not dye hair with PPD if you have reacted before. A 'natural' black dye or black henna tattoo can contain the same family and can sensitise you. Patch tests sold with the dye are not a perfect guarantee.",
        [C("always", "PPD is a serious hair-dye allergen. Do not use it if you have ever swollen, blistered, or struggled to breathe after a dye or a black henna tattoo. A small patch test in the kit is not a guarantee."),
         V("child", "Do not use permanent PPD hair dye on a child.")],
    ),
    ing(
        "hydrogen_peroxide",
        ["hydrogen peroxide"],
        "Hydrogen peroxide",
        "Other",
        "An oxidiser in hair dye developers and some tooth or ear products. Not a face serum ingredient.",
        "Can burn skin and hair at developer strengths.",
        "Use only as the dye system intends. Do not put developer on the face as a bleach.",
        [C("always", "Hydrogen peroxide at developer strength is a burn risk. It is not a skin-brightening cosmetic."),
         V("child", "Keep hair-dye developer away from children.")],
    ),
    ing(
        "resorcinol",
        ["resorcinol"],
        "Resorcinol",
        "Other",
        "Used in some hair dyes and in a few acne medicines. It can irritate and it is not a cosmetic to collect from a reel.",
        "Can burn on skin.",
        "Medical use, if any, belongs with a clinician. In hair dye it adds to the allergy burden of the dye.",
        [C("always", "Resorcinol is an irritant used in dyes and some medicines. Do not add it as a casual face treatment."),
         C("pregnancy", "Avoid cosmetic resorcinol in pregnancy."),
         V("child", "Do not use resorcinol products on a young child.")],
    ),
    ing(
        "ci_colorant",
        [],
        "Colour (CI number)",
        "Other",
        "Colour additives are written as CI followed by digits. This check does not judge every pigment separately.",
        "Colour is cosmetic. A rash from makeup can still be the fragrance or the preservative rather than the pigment.",
        "No treatment effect. If a specific colourant has bothered you before, type its CI number into your allergy notes.",
        [],
    ),
]
